services:
  - type: web
    name: website-builders-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
